# Foil Studio defaults. User files store overrides only.
# Connection.openserial enables automatic connection at startup.
[bCNC]
checkinterval = 30

[Connection]
firmware_mode = AUTO
baud = 115200
port =
openserial = 0
controller = GRBL1

[Plotter]
load_mode = auto
appearance = System
density = Comfortable

[Canvas]
workarea = 0
margin = 1
grid = 1
axes = 1
rapid = 1
paths = 1
drawtime = 5

[Error]

[File]
dir =
file =
dxfloopmerge = 0

[Editors]
librecad = librecad
inkscape = inkscape

[CNC]
units = 0
doublesizeicon = 0
acceleration_x = 25
acceleration_y = 25
acceleration_z = 50
feedmax_x = 3000
feedmax_y = 3000
feedmax_z = 2000
travel_x = 200
travel_y = 200
travel_z = 100
round = 4
accuracy = 0.01
startup = G90
header = M5
	G21 G90 G17 G94
footer = M5

[Font]
balloon = Sans,-12

[Color]
canvas.disable = LightGray
canvas.enable = Black
canvas.gantry = Red
canvas.grid = Gray
canvas.insert = Blue
canvas.margin = Magenta
canvas.move = DarkCyan
canvas.process = Green
canvas.ruler = Green
canvas.select = Blue
canvas.select2 = DarkCyan
canvas.selectbox = Cyan
canvas.background = White
global.background =
global.foreground =
global.activebackground =
global.activeforeground =
global.disabledforeground =
global.highlightbackground =
global.highlightcolor =
global.selectbackground =
global.selectforeground =
